spring:
  profiles:
    group:
      prod: "prod"
      dev: "dev"
      test: "test"

  main:
    web-application-type: none

  datasource:
    url: jdbc:mariadb://localhost:3306/dacobot
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO

  pattern:
    console: "%d{HH:mm:ss.SSS} %boldCyan(%-25.-25thread) %red(%10.10X{jda.shard}) %boldGreen(%-20.-20logger{0}) %highlight(%-6level) %msg%n"

  file:
    name: "./log/dacobot.log"

dacobot:
  jda:
    boot: true