spring:
  profiles:
    group:
      dev: "dev"
      prod: "prod"

  main:
    web-application-type: none

  datasource:
    url: jdbc:mariadb://localhost:3306/dacobot
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate

  test:
    database:
      replace: none
---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
