spring:
  profiles:
    group:
      prod: "prod"
      dev: "dev"
      test: "test"

  main:
    web-application-type: none

  datasource:
    url: jdbc:mariadb://localhost:3306/dacobot
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate

dacobot:
  jda:
    boot: true